fix: 헤로쿠 서버 에러로 추가
- SpringBoot 2.6 이상 springfox-swagger3.0 적용 시 `Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang
                                               .NullPointerException: Cannot invoke "org.springframework.web.servlet.mvc.condition
                                               .PatternsRequestCondition.getPatterns()" because "this.condition" is null` 에러가 발생한다.
 - 에러 발생 이유는 spring boot 2.6.0부터 요청 경로를 ControllerHandler 에 매칭시키기 위한 전략의 기본값이 ant_path_matcher 전략 -> path_pattern_parser 전략으로 변경되었기 때문이다.
 - 스프링부트의 버전을 낮추는 방법도 있지만 전략의 기본값을 변경하기로 함.